@BASEURL = {{${{$dotenv BACKEND_URL}}}}

POST {{BASEURL}}/auth/register
Content-Type: application/json

{
   "username": "kawasousa",
   "password": "KawaSousa3",
   "name": "Kawã Sousa - Dev",
   "icon": "chess-king",
   "role": "Admin"
}