## Create post
@BASEURL = {{${{$dotenv BACKEND_URL}}}}
@COOKIE = ""

POST {{BASEURL}}/posts/
Content-Type: application/json
Cookie: {{COOKIE}}

{
    "username": "jhondoe",
    "content": "My first post!"
}